//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interdisciplinary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class interdisciplinaryDBEntities : DbContext
    {
        public interdisciplinaryDBEntities()
            : base("name=interdisciplinaryDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<customer> customers { get; set; }
        public DbSet<lineitem> lineitems { get; set; }
        public DbSet<orderline> orderlines { get; set; }
        public DbSet<reservation> reservations { get; set; }
    }
}
