//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interdisciplinary
{
    using System;
    using System.Collections.Generic;
    
    public partial class lineitem
    {
        public lineitem()
        {
            this.orderlines = new HashSet<orderline>();
        }
    
        public int lineitemid { get; set; }
        public string name { get; set; }
        public decimal price { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<orderline> orderlines { get; set; }
    }
}
